config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/link_through'

  get 'profiles/show'

  get 'test/index'

  get 'test/edit'

  get 'comments/index'

  get 'comments/edit'

  get 'notifications', to: 'notifications#index'
  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'browse', to: 'posts#browse', as: :browse_posts

  #for something like john.com/arinze
  get ':user_name', to: 'profiles#show', as: :profile

  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  #get ":id/like", to: "posts#like", as: :like_post

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

  get 'notifications', to: 'notifications#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "posts#index"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_user_and_posts
	before_action :owned_profile, only: [:edit, :update]
	before_action :authenticate_user!
  def show
  	
  end

  def edit
  	
  end

  def update
  	if @user.update(profile_params)
		flash[:success] = 'Your profile has been updated.'
		redirect_to profile_path(@user.user_name)
	else
		@user.errors.full_messages
		flash[:error] = @user.errors.full_messages
		render :edit
	end
  end

  private
  def set_user_and_posts
  	@user = User.find_by(:user_name => params[:user_name])
  	@posts = @user.posts.order("created_at DESC")
  end
  def profile_params
	params.require(:user).permit(:avatar, :bio)
  end

  def owned_profile
	@user = User.find_by(user_name: params[:user_name])
	unless current_user == @user
	flash[:alert] = "That profile doesn't belong to you!"
	redirect_to root_path
  end
end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
  <div class = "posts-wrapper">
  	<div class="post">
  		<div class="post-body">
  			<div class="image-wrap">
  				
  				
  				<%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
  					<div class="row">
  						<div class="col-md-12 text-center">
  							<div class="form-group">
  								<h4> Change your profile avatar</h4>
  								<div class="img-circle">
  									<%= profile_avatar_select(@user) %>
  								</div>
  								<%= f.file_field :avatar, onChange: 'loadFile(event)'%>
  							</div>
  						</div>
  					</div>
  					<div class="row">
  						<div class="col-md-12 text-center">
  							<div class="form-group">
  								<h4> Update Your Bio</h4>
  								<%= f.text_area :bio, label: false, rows: 4 , class: "form-group text-center" %>
								<%= f.submit "Update Profile", class: 'btn btn-success' %>
  							</div>
  						</div>
  					</div>

  					
  				<% end %>
  			</div>
  		</div>
  	</div>
  </div>

app/views/profiles/show.html.erb
<div class="post-wrapper">
	<div class="row profile-header">
		<div class="col-md-6">
			<div class="img-circle">
				<%= profile_avatar_select(@user) %>
			</div>
		</div>
		<div class="col-md-6">
			<div class="user-name-and-follow">
				<h3 class="profile-user-name">
					<%= @user.user_name%>
				</h3>
				<span>
					<% if @user == current_user %>
						<%= link_to 'Edit Profile', edit_profile_path(@user.user_name), class: 'btn edit-button'%>
					<% else %>
					<% if current_user_is_following(current_user.id, @user.id) %>
						<%= link_to link_to 'Following', unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button',method: :post %>
					<% else %>
					<%= link_to 'Follow', follow_user_path, remote: true, class: 'btn follow-button', id: 'follow-button', method: :post %>
					<% end %>
					<% end %>
				</span>
			</div>

			<p class="profile-bio">
				<%= @user.bio %>
			</p>
			<div class="user-statistics row">
				<div class = "col-md-3">
				<p>
					<%= pluralize @user.posts.count, 'post' %>
				</p>
				</div>
				<div class = "col-md-3" id = "follower-count">
					<%= pluralize @user.followers.count, 'follower' %>
				</div>
				<div class = "col-md-3" id = "following-count">
					 <%= "#{@user.following.count} followers" %>
				</div>

			</div>
		</div>
	</div>
</div>


<div id="posts">
<% @posts.each do |post| %>
		<%= 
		render(:partial => 'posts/post' , :locals => {:post => post})
		 %>
		 <% end %>
	</div>