config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/link_through'

  get 'profiles/show'

  get 'test/index'

  get 'test/edit'

  get 'comments/index'

  get 'comments/edit'

  get 'notifications', to: 'notifications#index'
  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'browse', to: 'posts#browse', as: :browse_posts

  #for something like john.com/arinze
  get ':user_name', to: 'profiles#show', as: :profile

  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  #get ":id/like", to: "posts#like", as: :like_post

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

  get 'notifications', to: 'notifications#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "posts#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :op_user, class_name: "User"
  belongs_to :post

  validates :user_id, :op_user_id, :post_id, :notification_type, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  def link_through
	@notification = Notification.find(params[:id])
	@notification.update read: true
	redirect_to post_path @notification.post
  end

  def index
  	@notifications = current_user.notifications.order('created_at DESC')
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li>
<%= link_to notif_helper(notification), link_through_path(notification) %>
</li>

app/views/notifications/_notification_dropdown.html.erb
<li>
          <div class="dropdown notification-dropdown">
            <button class="btn btn-default dropdown-toggle"
              type = "button" id = "dropdownMenu1", data-toggle = "dropdown" aria-haspopup = "true"
              aria-expanded = "true">
              <%=current_user.notifications.where(:read => false).count%>
              <span class = "glyphicon glyphicon-flag"></span>
              </button>
            <ul class="dropdown-menu" aria-labelledby = "dropdownMenu1">
              <li class="dropdown-header text-center">
                Notifications
              </li>

              <% current_user.notifications.order('created_at DESC').where(:read => false).last(5).each do |notification| %>

                <%= render :partial => "notifications/notification", :locals => {:notification => notification} %>
                
              <% end %>
              
             
            <li class="divider" role = "separator">
            <li class="text-center">
              <%= link_to "View All", notifications_path %>
            </li>
            </li>

            </ul>

          </div>
        </li>

app/views/notifications/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<ul class="notification-index-list">
			<%= render @notifications %>
				
			</ul>
		</div>
	</div>
</div>

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>