config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/link_through'

  get 'profiles/show'

  get 'test/index'

  get 'test/edit'

  get 'comments/index'

  get 'comments/edit'

  get 'notifications', to: 'notifications#index'
  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'browse', to: 'posts#browse', as: :browse_posts

  #for something like john.com/arinze
  get ':user_name', to: 'profiles#show', as: :profile

  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  #get ":id/like", to: "posts#like", as: :like_post

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

  get 'notifications', to: 'notifications#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :user_id, presence: true
	validates :avatar, presence: true
	validates_length_of :caption, {:maximum => 300, :minimum => 3}
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    scope :of_followed_users, -> (following_users) { where user_id: following_users}


    acts_as_votable
    has_many :notifications, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :set_post , only: [:show, :edit, :update, :destroy, :like]
	before_action :authenticate_user!
	before_action :owned_post, only: [:edit, :update, :destroy]
	

	def index
		@posts = Post.of_followed_users(current_user.following).order('created_at DESC').page params[:page]
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Your post has been created!"
			redirect_to posts_path
		else
			flash[:alert] = "Your new post couldn't be created!
			Please check the form."
			render :new
		end
	end

	def browse
		@posts = Post.all.order('created_at DESC').page params[:page]
	end

	def show
		
	end


	def edit

	end

	def update
		
		if @post.update_attributes(post_params)
      		flash[:success] = "Your post has been updated!"
      		redirect_to  post_path(@post.id)
    	else
    		flash.now[:alert] = "Your new post couldn't be updated! Please check the form."
      		render('edit')
      	end
    end

    def destroy
    	@post.destroy
    	flash[:success] = "Your post has been deleted"
    	redirect_to  posts_path
	end

	def like
		if current_user.voted_for? @post
			@post.unliked_by current_user
			delete_notification(@post)
		else
			@post.liked_by current_user
			create_notification(@post)
			
		end
		#puts "im here"

		respond_to do |format|
      		format.html { redirect_to :back}
      		format.js
    	end
	end

	private
	def delete_notification(post)
    	unless current_user.id == post.user_id
      		notification = Notification.all.where(:notification_type => "like", :user_id => post.user_id, :op_user_id => current_user.id, :post_id => post.id)

      		notification.last.destroy
    end
  end
	def create_notification(post)
    	unless current_user.id == post.user_id
      		notification = Notification.new(:user_id => post.user_id, :op_user_id => current_user.id, :notification_type => "like", :post_id => post.id)
      		notification.save
    	end
  	end

	def post_params
		params.require(:post).permit(:avatar, :caption)
 	end

 	def set_post
 		@post = Post.find(params[:id])
 	end

 	def voter_list
 		@voters = @post.votes_for.voters

 	end

 	def owned_post
		unless current_user == @post.user
			flash[:alert] = "That post doesn't belong to you!"
			redirect_to root_path
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper


	# Our new helper method

	def display_likes(post)
		# votes variable is set to the likes by users.
		votes = post.votes_for.up.by_type(User)
		return list_likers(votes) if votes.size <= 8
		count_likers(votes)
	end

	def list_likers(votes)
		user_names = []
		# unless there are no likes, continue below.
		unless votes.blank?
			# iterate through the voters of each vote (the users who liked the post)
			votes.voters.each do |voter|
				# add the user_name as a link to the array
				user_names.push(link_to voter.user_name, profile_path(voter.user_name), class: 'user-name')
			end
			# present the array as a nice sentence using the as_sentence method and also make it usable within our html.
			#Then call the like_plural method with the votes variable we set
			#earlier as the argument.
			user_names.to_sentence.html_safe + like_plural(votes)
		end
	end

	def count_likers(votes)
		vote_count = votes.size
		vote_count.to_s + ' likes'
	end

	def liked_post(post)
		return "glyphicon-heart" if current_user.voted_for? post
        "glyphicon-heart-empty"
	end
	private

	def like_plural(votes)
		# If we more than one like for a post, use ' like this'
		return ' like this' if votes.count > 1
		# Otherwise, return ' likes this' 
		' likes this'
	end
end

app/views/posts/_form.html.erb
  <div class = "posts-wrapper">
  	<div class="post">
  		<div class="post-body">
  			<div class="image-wrap">
  				<%= form_image_select(@post) %>
  				
  				<%= simple_form_for @post, html: { multipart: true } do |f| %>
  					<div class="row">
  						<div class="col-md-12 text-center">
  							<%= f.error_notification%>
  						</div>
  					</div>

  					<div class="container-fluid">
  						<div class="form-group text-center">
  							<h4> Upload an image (this is required):</h4>
  							<%= f.input :avatar, label: false, input_html: { onChange: 'loadFile(event)' } %>
  						</div>
  						<div class="form-group text-center">
  							<%= form.input :caption , label: false, placeholder: 'Add your caption'%>
  						</div>

  						<div class="form-group text-center">
  							<%= form.button :submit , class: "btn-success"%>
  						</div>
  					</div>
  				<% end %>
  			</div>
  		</div>
  	</div>
  </div>

app/views/posts/_likes.html.erb
<div class = "likes" id = <%= "like_count_#{post.id}" %>>
					<%= display_likes post %>
					
					
				</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
	<div class="post">
		<div class="post-head">
			<div class="thumb-img"></div>
			<div class="user-name"> <%= link_to post.user.user_name, profile_path(post.user.user_name) %>

			</div>
			<div class="time-ago">
			<%= time_ago_in_words post.created_at %>
			</div>
		</div>
		<div class="image centre-block">
			<%= link_to (image_tag post.avatar.url(:medium), class:'img-responsive'), post_path(post) %>
		</div>
		<div class="post-bottom">
			<div class="caption">
				<div class="user-name">
					<%= link_to post.user.user_name, profile_path(post.user.user_name) %>
				</div>
				<%= post.caption %>
			</div>
				<%= render 'posts/likes', post: post %>
			
			
			<div class = "comments" id = <%= "comments_#{post.id}"%>>
			
			<% if post.comments.any?%>
				<div class="paginator" id = "comments-paginator-#{post.id}">
					<% unless post.comments.count <= 4 %>
				 		<%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: {post_id: "#{post.id}", type: "html"} %>
				 	<% end %>
				
				<%= render post.comments.last(4), post: post %>

				</div>
				
			<% end %>
			</div>

		</div>

		<div class="comment-like-form row">
			<div class="like-button col-sm-1 like-button">
				
			<%= link_to  like_post_path(post.id), method: :get,  remote: true do %>
			<%= content_tag(:span, class: "like glyphicon #{liked_post(post)}", id: "like_#{post.id}") do %>
			<% end %>						
			<%end%>
				</div>
			
			<div class="comment-form col-sm-11">
				<%= form_for [post, post.comments.new], remote: true  do |f| %>
					<%= f.text_field :content, placeholder: 'Add a comment...' , class: "comment_content", id: "comment_content_#{post.id}"%>
				<%  end %>
			</div>
			
		</div>
		
	</div>
</div>

app/views/posts/_post_dashboard.html.erb
	
	<div id="posts">
		<%= render(:partial => 'posts') %>
	</div>

	<div id="paginator" class = "text-center">
		<%= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
	</div>
	

app/views/posts/_post_dashboard.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%=
escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote:
true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
		<%= render(:partial => 'post', :locals => {:post => post}) %>

	<% end %>

app/views/posts/browse.html.erb
<%= render 'post_dashboard', posts: @posts %>

app/views/posts/edit.html.erb
<div class="form-wrapper">
<%= simple_form_for @post, html: { class: 'form-horizontal',
multipart: true }, url: post_path(@post.id) do |form| %>

 
  <%= render(:partial => 'form', :locals => {:form => form}) %>

<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete,
data: { confirm: "Are you sure you want to delete this post?" } %>
</div>

  

<% end %>

</div>

app/views/posts/index.html.erb
		<%= render 'post_dashboard', posts: @posts %>
	

app/views/posts/like.js.erb
$("#like_count_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");
$("#like_<%= @post.id %>").toggleClass('glyphicon-heart');
$("#like_<%= @post.id %>").toggleClass('glyphicon-heart-empty');

app/views/posts/new.html.erb
<div class="form-wrapper">
<%= simple_form_for @post,html: { class: 'form-horizontal',
multipart: true }, url: posts_path do |form| %>
  <%= render(:partial => 'form', :locals => {:form => form}) %>

  

<% end %>

</div>

app/views/posts/show.html.erb
		<%= render(:partial => 'post', :locals => {:post => @post}) %>
			<div class="text-center edit-links">
			<%= link_to "Cancel", posts_path %>
			<% if current_user.id == @post.user.id %>
				<%= link_to "Edit Post", edit_post_path(@post) %>
			<% end %>
		</div>